name: Deploy to Aliyun Docker Registry

on:
  push:
    branches:
      - main  # 触发条件，例如推送至 main 分支

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Aliyun Docker Registry
      run: echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login --username ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password-stdin ${{ secrets.ALIYUN_DOCKER_REGISTRY }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ALIYUN_DOCKER_REGISTRY }}/${{ secrets.ALIYUN_DOCKER_IMAGE }}:${{ github.sha }} .
        docker push ${{ secrets.ALIYUN_DOCKER_REGISTRY }}/${{ secrets.ALIYUN_DOCKER_IMAGE }}:${{ github.sha }}

    - name: Tag and push latest
      run: |
        docker tag ${{ secrets.ALIYUN_DOCKER_REGISTRY }}/${{ secrets.ALIYUN_DOCKER_IMAGE }}:${{ github.sha }} ${{ secrets.ALIYUN_DOCKER_REGISTRY }}/${{ secrets.ALIYUN_DOCKER_IMAGE }}:latest
        docker push ${{ secrets.ALIYUN_DOCKER_REGISTRY }}/${{ secrets.ALIYUN_DOCKER_IMAGE }}:latest